// <auto-generated />
using System;
using FilmFinder.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FilmFinder.Migrations
{
    [DbContext(typeof(FilmFinderContext))]
    partial class FilmFinderContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("FilmFinder.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Suspense"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Drama"
                        });
                });

            modelBuilder.Entity("FilmFinder.Models.Movie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("TEXT");

                    b.Property<int?>("GenreId")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("PictureName")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Year")
                        .IsRequired()
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A thief who steals corporate secrets through the use of dream-sharing technology is given the inverse task of planting an idea into the mind of a C.E.O.",
                            GenreId = 2,
                            Name = "Inception",
                            PictureName = "inception.jpg",
                            Rating = 8,
                            Year = 2010
                        },
                        new
                        {
                            Id = 2,
                            Description = "When the menace known as the Joker emerges from his mysterious past, he wreaks havoc and chaos on the people of Gotham.",
                            GenreId = 1,
                            Name = "The Dark Knight",
                            PictureName = "the_dark_knight.jpg",
                            Rating = 9,
                            Year = 2008
                        },
                        new
                        {
                            Id = 3,
                            Description = "The lives of two mob hitmen, a boxer, a gangster's wife, and a pair of diner bandits intertwine in four tales of violence and redemption.",
                            GenreId = 3,
                            Name = "Pulp Fiction",
                            PictureName = "pulp_fiction.jpg",
                            Rating = 9,
                            Year = 1994
                        },
                        new
                        {
                            Id = 4,
                            Description = "The aging patriarch of an organized crime dynasty transfers control of his clandestine empire to his reluctant son.",
                            GenreId = 5,
                            Name = "The Godfather",
                            PictureName = "the_godfather.jpg",
                            Rating = 9,
                            Year = 1972
                        },
                        new
                        {
                            Id = 5,
                            Description = "Three buddies wake up from a bachelor party in Las Vegas, with no memory of the previous night and the bachelor missing.",
                            GenreId = 4,
                            Name = "The Hangover",
                            PictureName = "the_hangover.jpg",
                            Rating = 7,
                            Year = 2009
                        },
                        new
                        {
                            Id = 6,
                            Description = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            GenreId = 2,
                            Name = "Interstellar",
                            PictureName = "interstellar.jpg",
                            Rating = 8,
                            Year = 2014
                        },
                        new
                        {
                            Id = 7,
                            Description = "A computer hacker learns from mysterious rebels about the true nature of his reality and his role in the war against its controllers.",
                            GenreId = 2,
                            Name = "The Matrix",
                            PictureName = "the_matrix.jpg",
                            Rating = 8,
                            Year = 1999
                        },
                        new
                        {
                            Id = 8,
                            Description = "The presidencies of Kennedy and Johnson, the events of Vietnam, Watergate, and other historical events unfold through the perspective of an Alabama man with an IQ of 75.",
                            GenreId = 5,
                            Name = "Forrest Gump",
                            PictureName = "forrest_gump.jpg",
                            Rating = 8,
                            Year = 1994
                        },
                        new
                        {
                            Id = 9,
                            Description = "A former Roman General sets out to exact vengeance against the corrupt emperor who murdered his family and sent him into slavery.",
                            GenreId = 1,
                            Name = "Gladiator",
                            PictureName = "gladiator.jpg",
                            Rating = 8,
                            Year = 2000
                        },
                        new
                        {
                            Id = 10,
                            Description = "Two imprisoned men bond over a number of years, finding solace and eventual redemption through acts of common decency.",
                            GenreId = 5,
                            Name = "The Shawshank Redemption",
                            PictureName = "the_shawshank_redemption.jpg",
                            Rating = 9,
                            Year = 1994
                        });
                });

            modelBuilder.Entity("FilmFinder.Models.Movie", b =>
                {
                    b.HasOne("FilmFinder.Models.Genre", "Genre")
                        .WithMany()
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genre");
                });
#pragma warning restore 612, 618
        }
    }
}
